swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /:
        post:
            tags:
                - calc
            summary: divide calc
            operationId: calc#divide
            parameters:
                - name: DivideRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CalcDivideRequestBody'
                    required:
                        - dividend
                        - divisor
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CalcDivideResponseBody'
                        required:
                            - quotient
                            - reminder
                "400":
                    description: Response used for division by zero errors
                    schema:
                        $ref: '#/definitions/CalcDivideDivByZeroResponseBody'
                        required:
                            - message
                "504":
                    description: Operation timed out
                    schema:
                        $ref: '#/definitions/CalcDivideTimeoutResponseBody'
            schemes:
                - http
definitions:
    CalcDivideDivByZeroResponseBody:
        title: CalcDivideDivByZeroResponseBody
        type: object
        properties:
            message:
                type: string
                description: division by zero leads to infinity.
                example: Alias incidunt.
        description: division by 0
        example:
            message: Non et.
        required:
            - message
    CalcDivideRequestBody:
        title: CalcDivideRequestBody
        type: object
        properties:
            dividend:
                type: integer
                example: 6836512047429743720
                format: int64
            divisor:
                type: integer
                example: 7054049476353626766
                format: int64
        example:
            dividend: 5570723899899913296
            divisor: 6513733567661029654
        required:
            - dividend
            - divisor
    CalcDivideResponseBody:
        title: CalcDivideResponseBody
        type: object
        properties:
            quotient:
                type: integer
                example: 7617773024289378824
                format: int64
            reminder:
                type: integer
                example: 8614350958614154271
                format: int64
        example:
            quotient: 4285228716133201605
            reminder: 1232634558296710584
        required:
            - quotient
            - reminder
    CalcDivideTimeoutResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: divide_timeout_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
