language: go
dist: xenial
go:
- "1.14.x"
cache:
  directories:
    - $HOME/gopath/pkg
    - $HOME/gopath/src/bitbucket.org
    - $HOME/gopath/src/cloud.google.com
    - $HOME/gopath/src/github.com/aws
    - $HOME/gopath/src/github.com/golang
    - $HOME/gopath/src/github.com/googleapis
    - $HOME/gopath/src/github.com/hashicorp
    - $HOME/gopath/src/github.com/mitchellh
    - $HOME/gopath/src/github.com/ulikunitz
    - $HOME/gopath/src/github.com/cheggaaa
    - $HOME/gopath/src/github.com/mattn
    - $HOME/gopath/src/golang.org
    - $HOME/gopath/src/google.golang.org
    - $HOME/gopath/src/gopkg.in
    - $HOME/gopath/src/honnef.co
    - $HOME/gopath/src/k8s.io
script:
- export PATH=${PATH}:${HOME}/bin:${HOME}/gopath/bin
- cd ../../.. && mkdir goa.design && cp -r github.com/goadesign/examples goa.design/examples
- cd goa.design/examples
- make travis
