openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for openapi
paths:
    /openapi.json:
        get:
            tags:
                - openapi
            summary: Download gen/http/openapi.json
            operationId: openapi#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /openapi.yaml:
        get:
            tags:
                - openapi
            summary: Download gen/http/openapi.yaml
            operationId: openapi#/openapi.yaml
            responses:
                "200":
                    description: File downloaded
    /openapi3.json:
        get:
            tags:
                - openapi
            summary: Download gen/http/openapi3.json
            operationId: openapi#/openapi3.json
            responses:
                "200":
                    description: File downloaded
    /openapi3.yaml:
        get:
            tags:
                - openapi
            summary: Download gen/http/openapi3.yaml
            operationId: openapi#/openapi3.yaml
            responses:
                "200":
                    description: File downloaded
components: {}
tags:
    - name: openapi
