swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /openapi.json:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi.json
      operationId: openapi#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /openapi.yaml:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi.yaml
      operationId: openapi#/openapi.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /openapi3.json:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi3.json
      operationId: openapi#/openapi3.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /openapi3.yaml:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi3.yaml
      operationId: openapi#/openapi3.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
